In [1]:
import csv
import os
import requests
from bs4 import BeautifulSoup
import traceback

In [2]:
url_str = 'https://www.carwale.com/'
company_names = ['audi', 'bmw', 'chevrolet', 'datsun', 'fiat', 'forcemotors', 'ford', 'honda', 'hyundai', 'jaguar', 'landrover', 'mahindra', 'marutisuzuki', 'mercedesbenz', 'mitsubishi', 'nissan', 'renault', 'skoda', 'tata', 'toyota', 'volkswagen', 'volvo']

In [3]:
companies = len(company_names)

In [4]:
cc = 0 # company-count

all_url = []
while cc < companies:
    all_url.append(url_str + company_names[cc] + '-cars/')
    cc = cc + 1

In [5]:
print(all_url)

['https://www.carwale.com/audi-cars/', 'https://www.carwale.com/bmw-cars/', 'https://www.carwale.com/chevrolet-cars/', 'https://www.carwale.com/datsun-cars/', 'https://www.carwale.com/fiat-cars/', 'https://www.carwale.com/forcemotors-cars/', 'https://www.carwale.com/ford-cars/', 'https://www.carwale.com/honda-cars/', 'https://www.carwale.com/hyundai-cars/', 'https://www.carwale.com/jaguar-cars/', 'https://www.carwale.com/landrover-cars/', 'https://www.carwale.com/mahindra-cars/', 'https://www.carwale.com/marutisuzuki-cars/', 'https://www.carwale.com/mercedesbenz-cars/', 'https://www.carwale.com/mitsubishi-cars/', 'https://www.carwale.com/nissan-cars/', 'https://www.carwale.com/renault-cars/', 'https://www.carwale.com/skoda-cars/', 'https://www.carwale.com/tata-cars/', 'https://www.carwale.com/toyota-cars/', 'https://www.carwale.com/volkswagen-cars/', 'https://www.carwale.com/volvo-cars/']

In [6]:
full_list = []

In [7]:

def car_detail(car_url):	# returns a list
	details = []
	src = requests.get(car_url)
	soup = BeautifulSoup(src.text, 'lxml')

	span_found = soup.findAll('span', {'itemprop': 'title'})
	comp_str = span_found[1].text
	car_str = str(span_found[2].text)[1:]
	details.extend([comp_str, car_str])
	try:
		variants = soup.select('a.font14.text-bold')
		start = 0
		end = len(variants)
		total = 0
		print('end')
		print(end)
		prices_span = soup.findAll('span', {'class': 'text-bold'})[start:end]
		for span in prices_span:
			print('span')
			print(span)
			str_price = str(span.text).replace(' ', '').replace('\n', '').replace('\r', '')
			print('str_rice')
			print(str_price[:-1])
			# if price is L
			if str_price[-1] == 'L'	:
				int_price = int(float(str_price[:-1]) * 100000)
			else:
				int_price = int(float(str_price[:-2]) * 10000000)

			print('int price')
			print (int_price)
			total = total+int_price
		print ('total')
		print(total)
		avg_price = int(total/len(variants))
		print('avg_price')
		print(avg_price)
	except:
		traceback.print_exc()
		print ('in except')
		details.append(-1)
		# will remove the list out later
		return details
	details.append(avg_price)

	return details

In [8]:

def get_cars():
	for the_url in all_url:
		print('the url')
		print(the_url)
		src = requests.get(the_url)
		soup = BeautifulSoup(src.text, 'lxml')
		for link in soup.findAll('a', {'class': 'font18'}):
			href = str('http://www.carwale.com' + link.get('href'))
			car_name = str(link.string)
			detail_list = []
			detail_list = car_detail(href)
			if detail_list[2] != -1:
				full_list.append(detail_list)
				print('added ' + detail_list[0] + ' ' + detail_list[1])
			else:
				print('price not found for ' + detail_list[0] + ' ' + detail_list[1])

In [ ]:
get_cars()

the url
https://www.carwale.com/audi-cars/
end
4
span
<span class="text-bold">
                                            27.81L
                                        </span>
str_rice
27.81
int price
2781000
span
<span class="text-bold">
                                            30.06L
                                        </span>
str_rice
30.06
int price
3006000
span
<span class="text-bold">
                                            33.76L
                                        </span>
str_rice
33.76
int price
3376000
span
<span class="text-bold">
                                            36.54L
                                        </span>
str_rice
36.54
int price
3654000
total
12817000
avg_price
3204250
added Audi A3
end
5
span
<span class="text-bold">
                                            31.28L
                                        </span>
str_rice
31.28
int price
3128000
span
<span class="text-bold">
                                            35.14L
                                        </span>
str_rice
35.14
int price
3514000
span
<span class="text-bold">
                                            36.72L
                                        </span>
str_rice
36.72
int price
3672000
span
<span class="text-bold">
                                            39.24L
                                        </span>
str_rice
39.24
int price
3924000
span
<span class="text-bold">
                                            42.03L
                                        </span>
str_rice
42.03
int price
4203000
total
18441000
avg_price
3688200
added Audi Q3
end
2
span
<span class="text-bold">
                                            39.01L
                                        </span>
str_rice
39.01
int price
3901000
span
<span class="text-bold">
                                            42.19L
                                        </span>
str_rice
42.19
int price
4219000
total
8120000
avg_price
4060000
added Audi A4
end
1
span
<span class="text-bold">
                                            48.45L
                                        </span>
str_rice
48.45
int price
4845000
total
4845000
avg_price
4845000
added Audi A3 Cabriolet
end
3
span
<span class="text-bold">
                                            49.59L
                                        </span>
str_rice
49.59
int price
4959000
span
<span class="text-bold">
                                            52.75L
                                        </span>
str_rice
52.75
int price
5275000
span
<span class="text-bold">
                                            56.72L
                                        </span>
str_rice
56.72
int price
5672000
total
15906000
avg_price
5302000
added Audi Q5
end
2
span
<span class="text-bold">
                                            53.72L
                                        </span>
str_rice
53.72
int price
5372000
span
<span class="text-bold">
                                            53.96L
                                        </span>
str_rice
53.96
int price
5396000
total
10768000
avg_price
5384000
added Audi A6
end
1
span
<span class="text-bold">
                                            64.97L
                                        </span>
str_rice
64.97
int price
6497000
total
6497000
avg_price
6497000
added Audi TT
end
1
span
<span class="text-bold">
                                            67.72L
                                        </span>
str_rice
67.72
int price
6772000
total
6772000
avg_price
6772000
added Audi S5 Sportback
end
2
span
<span class="text-bold">
                                            74.40L
                                        </span>
str_rice
74.40
int price
7440000
span
<span class="text-bold">
                                            82.50L
                                        </span>
str_rice
82.50
int price
8250000
total
15690000
avg_price
7845000
added Audi Q7
end
5
span
<span class="text-bold">
                                            1.18Cr
                                        </span>
str_rice
1.18C
int price
11800000
span
<span class="text-bold">
                                            1.24Cr
                                        </span>
str_rice
1.24C
int price
12400000
span
<span class="text-bold">
                                            1.44Cr
                                        </span>
str_rice
1.44C
int price
14400000
span
<span class="text-bold">
                                            1.49Cr
                                        </span>
str_rice
1.49C
int price
14900000
span
<span class="text-bold">
                                            2.02Cr
                                        </span>
str_rice
2.02C
int price
20200000
total
73700000
avg_price
14740000
added Audi A8 L
end
1
span
<span class="text-bold">
                                            1.45Cr
                                        </span>
str_rice
1.45C
int price
14500000
total
14500000
avg_price
14500000
added Audi RS6
end
1
span
<span class="text-bold">
                                            1.56Cr
                                        </span>
str_rice
1.56C
int price
15600000
total
15600000
avg_price
15600000
added Audi RS7 Sportback
end
1
span
<span class="text-bold">
                                            2.61Cr
                                        </span>
str_rice
2.61C
int price
26100000
total
26100000
avg_price
26100000
added Audi R8
the url
https://www.carwale.com/bmw-cars/
end
4
span
<span class="text-bold">
                                            30.87L
                                        </span>
str_rice
30.87
int price
3087000
span
<span class="text-bold">
                                            35.41L
                                        </span>
str_rice
35.41
int price
3540999
span
<span class="text-bold">
                                            37.44L
                                        </span>
str_rice
37.44
int price
3744000
span
<span class="text-bold">
                                            41.50L
                                        </span>
str_rice
41.50
int price
4150000
total
14521999
avg_price
3630499
added BMW X1
end
1
span
<span class="text-bold">
                                            31.09L
                                        </span>
str_rice
31.09
int price
3109000
total
3109000
avg_price
3109000
added BMW 1 Series
end
7
span
<span class="text-bold">
                                            37.34L
                                        </span>
str_rice
37.34
int price
3734000
span
<span class="text-bold">
                                            37.65L
                                        </span>
str_rice
37.65
int price
3765000
span
<span class="text-bold">
                                            43.20L
                                        </span>
str_rice
43.20
int price
4320000
span
<span class="text-bold">
                                            43.20L
                                        </span>
str_rice
43.20
int price
4320000
span
<span class="text-bold">
                                            43.56L
                                        </span>
str_rice
43.56
int price
4356000
span
<span class="text-bold">
                                            46.41L
                                        </span>
str_rice
46.41
int price
4641000
span
<span class="text-bold">
                                            1.26Cr
                                        </span>
str_rice
1.26C
int price
12600000
total
37736000
avg_price
5390857
added BMW 3 Series
end
3
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for BMW 3 Series GT

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
4
span
<span class="text-bold">
                                            48.33L
                                        </span>
str_rice
48.33
int price
4833000
span
<span class="text-bold">
                                            54.46L
                                        </span>
str_rice
54.46
int price
5446000
span
<span class="text-bold">
                                            56.01L
                                        </span>
str_rice
56.01
int price
5601000
span
<span class="text-bold">
                                            61.68L
                                        </span>
str_rice
61.68
int price
6168000
total
22048000
avg_price
5512000
added BMW X3
end
6
span
<span class="text-bold">
                                            51.06L
                                        </span>
str_rice
51.06
int price
5106000
span
<span class="text-bold">
                                            53.74L
                                        </span>
str_rice
53.74
int price
5374000
span
<span class="text-bold">
                                            55.01L
                                        </span>
str_rice
55.01
int price
5501000
span
<span class="text-bold">
                                            55.07L
                                        </span>
str_rice
55.07
int price
5507000
span
<span class="text-bold">
                                            62.03L
                                        </span>
str_rice
62.03
int price
6203000
span
<span class="text-bold">
                                            1.37Cr
                                        </span>
str_rice
1.37C
int price
13700000
total
41391000
avg_price
6898500
added BMW 5 Series
end
6
span
<span class="text-bold">
                                            68.62L
                                        </span>
str_rice
68.62
int price
6862000
span
<span class="text-bold">
                                            73.46L
                                        </span>
str_rice
73.46
int price
7345999
span
<span class="text-bold">
                                            74.49L
                                        </span>
str_rice
74.49
int price
7448999
span
<span class="text-bold">
                                            76.54L
                                        </span>
str_rice
76.54
int price
7654000
span
<span class="text-bold">
                                            79.23L
                                        </span>
str_rice
79.23
int price
7923000
span
<span class="text-bold">
                                            1.58Cr
                                        </span>
str_rice
1.58C
int price
15800000
total
53033998
avg_price
8838999
added BMW X5
end
2
span
<span class="text-bold">
                                            77.71L
                                        </span>
str_rice
77.71
int price
7770999
span
<span class="text-bold">
                                            78.72L
                                        </span>
str_rice
78.72
int price
7872000
total
15642999
avg_price
7821499
added BMW Z4
end
7
span
<span class="text-bold">
                                            1.15Cr
                                        </span>
str_rice
1.15C
int price
11500000
span
<span class="text-bold">
                                            1.24Cr
                                        </span>
str_rice
1.24C
int price
12400000
span
<span class="text-bold">
                                            1.25Cr
                                        </span>
str_rice
1.25C
int price
12500000
span
<span class="text-bold">
                                            1.28Cr
                                        </span>
str_rice
1.28C
int price
12800000
span
<span class="text-bold">
                                            1.45Cr
                                        </span>
str_rice
1.45C
int price
14500000
span
<span class="text-bold">
                                            1.56Cr
                                        </span>
str_rice
1.56C
int price
15600000
span
<span class="text-bold">
                                            1.61Cr
                                        </span>
str_rice
1.61C
int price
16100000
total
95400000
avg_price
13628571
added BMW 7 Series
end
3
span
<span class="text-bold">
                                            1.16Cr
                                        </span>
str_rice
1.16C
int price
11600000
span
<span class="text-bold">
                                            1.23Cr
                                        </span>
str_rice
1.23C
int price
12300000
span
<span class="text-bold">
                                            1.79Cr
                                        </span>
str_rice
1.79C
int price
17900000
total
41800000
avg_price
13933333
added BMW 6 Series
end
2
span
<span class="text-bold">
                                            1.21Cr
                                        </span>
str_rice
1.21C
int price
12100000
span
<span class="text-bold">
                                            1.69Cr
                                        </span>
str_rice
1.69C
int price
16900000
total
29000000
avg_price
14500000
added BMW X6
end
1
span
<span class="text-bold">
                                            1.28Cr
                                        </span>
str_rice
1.28C
int price
12800000
total
12800000
avg_price
12800000
added BMW M4
end
1
span
<span class="text-bold">
                                            2.26Cr
                                        </span>
str_rice
2.26C
int price
22599999
total
22599999
avg_price
22599999
added BMW i8
the url
https://www.carwale.com/chevrolet-cars/
end
3
span
<span class="text-bold">
                                            3.73L
                                        </span>
str_rice
3.73
int price
373000
span
<span class="text-bold">
                                            4.01L
                                        </span>
str_rice
4.01
int price
401000
span
<span class="text-bold">
                                            4.32L
                                        </span>
str_rice
4.32
int price
432000
total
1206000
avg_price
402000
added Chevrolet Spark
end
8
span
<span class="text-bold">
                                            4.09L
                                        </span>
str_rice
4.09
int price
409000
span
<span class="text-bold">
                                            4.43L
                                        </span>
str_rice
4.43
int price
443000
span
<span class="text-bold">
                                            5L
                                        </span>
str_rice
5
int price
500000
span
<span class="text-bold">
                                            5.11L
                                        </span>
str_rice
5.11
int price
511000
span
<span class="text-bold">
                                            5.46L
                                        </span>
str_rice
5.46
int price
546000
span
<span class="text-bold">
                                            5.48L
                                        </span>
str_rice
5.48
int price
548000
span
<span class="text-bold">
                                            5.79L
                                        </span>
str_rice
5.79
int price
579000
span
<span class="text-bold">
                                            6.53L
                                        </span>
str_rice
6.53
int price
653000
total
4189000
avg_price
523625
added Chevrolet Beat
end
8
span
<span class="text-bold">
                                            4.91L
                                        </span>
str_rice
4.91
int price
491000
span
<span class="text-bold">
                                            5.43L
                                        </span>
str_rice
5.43
int price
543000
span
<span class="text-bold">
                                            5.67L
                                        </span>
str_rice
5.67
int price
567000
span
<span class="text-bold">
                                            6.06L
                                        </span>
str_rice
6.06
int price
606000
span
<span class="text-bold">
                                            6.38L
                                        </span>
str_rice
6.38
int price
638000
span
<span class="text-bold">
                                            6.61L
                                        </span>
str_rice
6.61
int price
661000
span
<span class="text-bold">
                                            6.77L
                                        </span>
str_rice
6.77
int price
677000
span
<span class="text-bold">
                                            7.64L
                                        </span>
str_rice
7.64
int price
764000
total
4947000
avg_price
618375
added Chevrolet Sail Hatchback
end
8
span
<span class="text-bold">
                                            5.89L
                                        </span>
str_rice
5.89
int price
589000
span
<span class="text-bold">
                                            6.46L
                                        </span>
str_rice
6.46
int price
646000
span
<span class="text-bold">
                                            6.85L
                                        </span>
str_rice
6.85
int price
685000
span
<span class="text-bold">
                                            7.22L
                                        </span>
str_rice
7.22
int price
722000
span
<span class="text-bold">
                                            7.34L
                                        </span>
str_rice
7.34
int price
734000
span
<span class="text-bold">
                                            7.65L
                                        </span>
str_rice
7.65
int price
765000
span
<span class="text-bold">
                                            7.99L
                                        </span>
str_rice
7.99
int price
799000
span
<span class="text-bold">
                                            8.62L
                                        </span>
str_rice
8.62
int price
861999
total
5801999
avg_price
725249
added Chevrolet Sail
end
6
span
<span class="text-bold">
                                            6.53L
                                        </span>
str_rice
6.53
int price
653000
span
<span class="text-bold">
                                            6.54L
                                        </span>
str_rice
6.54
int price
654000
span
<span class="text-bold">
                                            7.16L
                                        </span>
str_rice
7.16
int price
716000
span
<span class="text-bold">
                                            7.16L
                                        </span>
str_rice
7.16
int price
716000
span
<span class="text-bold">
                                            7.77L
                                        </span>
str_rice
7.77
int price
777000
span
<span class="text-bold">
                                            7.78L
                                        </span>
str_rice
7.78
int price
778000
total
4294000
avg_price
715666
added Chevrolet Enjoy
end
9
span
<span class="text-bold">
                                            8.13L
                                        </span>
str_rice
8.13
int price
813000
span
<span class="text-bold">
                                            8.13L
                                        </span>
str_rice
8.13
int price
813000
span
<span class="text-bold">
                                            9.06L
                                        </span>
str_rice
9.06
int price
906000
span
<span class="text-bold">
                                            9.06L
                                        </span>
str_rice
9.06
int price
906000
span
<span class="text-bold">
                                            9.93L
                                        </span>
str_rice
9.93
int price
993000
span
<span class="text-bold">
                                            9.93L
                                        </span>
str_rice
9.93
int price
993000
span
<span class="text-bold">
                                            10.22L
                                        </span>
str_rice
10.22
int price
1022000
span
<span class="text-bold">
                                            10.33L
                                        </span>
str_rice
10.33
int price
1033000
span
<span class="text-bold">
                                            11.34L
                                        </span>
str_rice
11.34
int price
1134000
total
8613000
avg_price
957000
added Chevrolet Tavera
end
3
span
<span class="text-bold">
                                            13.36L
                                        </span>
str_rice
13.36
int price
1336000
span
<span class="text-bold">
                                            14.65L
                                        </span>
str_rice
14.65
int price
1465000
span
<span class="text-bold">
                                            15.75L
                                        </span>
str_rice
15.75
int price
1575000
total
4376000
avg_price
1458666
added Chevrolet Cruze
end
1
span
<span class="text-bold">
                                            24.62L
                                        </span>
str_rice
24.62
int price
2462000
total
2462000
avg_price
2462000
added Chevrolet Trailblazer
the url
https://www.carwale.com/datsun-cars/
end
6
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Datsun Redi-GO

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
6
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Datsun GO

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
6
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Datsun GO Plus
the url
https://www.carwale.com/fiat-cars/

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
2
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Fiat Punto Pure

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
4
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Fiat Punto Evo

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
3
span
<span class="block text-bold font16"><span class="price-quote-all-imgs circle-call-icon"></span>18002090230</span>
str_rice
1800209023
int price
1800209020000000
span
<span class="text-bold">
                                            6.57L
                                        </span>
str_rice
6.57
int price
657000
span
<span class="text-bold">
                                            7.63L
                                        </span>
str_rice
7.63
int price
763000
total
1800209021420000
avg_price
600069673806666
added Fiat Linea Classic
end
4
span
<span class="block text-bold font16"><span class="price-quote-all-imgs circle-call-icon"></span>18002090230</span>
str_rice
1800209023
int price
1800209020000000
span
<span class="text-bold">
                                            7.04L
                                        </span>
str_rice
7.04
int price
704000
span
<span class="text-bold">
                                            7.66L
                                        </span>
str_rice
7.66
int price
766000
span
<span class="text-bold">
                                            8.29L
                                        </span>
str_rice
8.29
int price
828999
total
1800209022298999
avg_price
450052255574749
added Fiat Urban Cross
end
4
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Fiat Avventura

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
5
span
<span class="block text-bold font16"><span class="price-quote-all-imgs circle-call-icon"></span>18002090230</span>
str_rice
1800209023
int price
1800209020000000
span
<span class="text-bold">
                                            7.57L
                                        </span>
str_rice
7.57
int price
757000
span
<span class="text-bold">
                                            8.97L
                                        </span>
str_rice
8.97
int price
897000
span
<span class="text-bold">
                                            9.68L
                                        </span>
str_rice
9.68
int price
968000
span
<span class="text-bold">
                                            10.19L
                                        </span>
str_rice
10.19
int price
1019000
total
1800209023641000
avg_price
360041804728200
added Fiat Linea
end
1
span
<span class="block text-bold font16"><span class="price-quote-all-imgs circle-call-icon"></span>18002090230</span>
str_rice
1800209023
int price
1800209020000000
total
1800209020000000
avg_price
1800209020000000
added Fiat Abarth Punto
end
1
span
<span class="block text-bold font16"><span class="price-quote-all-imgs circle-call-icon"></span>18002090230</span>
str_rice
1800209023
int price
1800209020000000
total
1800209020000000
avg_price
1800209020000000
added Fiat Abarth 595
the url
https://www.carwale.com/forcemotors-cars/
end
3
span
<span class="text-bold">
                                            6.39L
                                        </span>
str_rice
6.39
int price
639000
span
<span class="text-bold">
                                            8.51L
                                        </span>
str_rice
8.51
int price
851000
span
<span class="text-bold">
                                            8.67L
                                        </span>
str_rice
8.67
int price
867000
total
2357000
avg_price
785666
added Force Motors Gurkha
end
4
span
<span class="text-bold">
                                            9.48L
                                        </span>
str_rice
9.48
int price
948000
span
<span class="text-bold">
                                            12.55L
                                        </span>
str_rice
12.55
int price
1255000
span
<span class="text-bold">
                                            12.66L
                                        </span>
str_rice
12.66
int price
1266000
span
<span class="text-bold">
                                            14.26L
                                        </span>
str_rice
14.26
int price
1426000
total
4895000
avg_price
1223750
added Force Motors Force One
the url
https://www.carwale.com/ford-cars/
end
15
span
<span class="block text-bold font16"><span class="price-quote-all-imgs circle-call-icon"></span>18002090230</span>
str_rice
1800209023
int price
1800209020000000
span
<span class="text-bold">
                                            4.71L
                                        </span>
str_rice
4.71
int price
471000
span
<span class="text-bold">
                                            5.01L
                                        </span>
str_rice
5.01
int price
501000
span
<span class="text-bold">
                                            5.17L
                                        </span>
str_rice
5.17
int price
517000
span
<span class="text-bold">
                                            5.55L
                                        </span>
str_rice
5.55
int price
555000
span
<span class="text-bold">
                                            5.79L
                                        </span>
str_rice
5.79
int price
579000
span
<span class="text-bold">
                                            5.92L
                                        </span>
str_rice
5.92
int price
592000
span
<span class="text-bold">
                                            6.15L
                                        </span>
str_rice
6.15
int price
615000
span
<span class="text-bold">
                                            6.19L
                                        </span>
str_rice
6.19
int price
619000
span
<span class="text-bold">
                                            6.33L
                                        </span>
str_rice
6.33
int price
633000
span
<span class="text-bold">
                                            6.49L
                                        </span>
str_rice
6.49
int price
649000
span
<span class="text-bold">
                                            6.59L
                                        </span>
str_rice
6.59
int price
659000
span
<span class="text-bold">
                                            6.80L
                                        </span>
str_rice
6.80
int price
680000
span
<span class="text-bold">
                                            7.06L
                                        </span>
str_rice
7.06
int price
706000
span
<span class="text-bold">
                                            7.42L
                                        </span>
str_rice
7.42
int price
742000
total
1800209028518000
avg_price
120013935234533
added Ford Figo
end
13
span
<span class="block text-bold font16"><span class="price-quote-all-imgs circle-call-icon"></span>18002090230</span>
str_rice
1800209023
int price
1800209020000000
span
<span class="text-bold">
                                            5.47L
                                        </span>
str_rice
5.47
int price
547000
span
<span class="text-bold">
                                            5.64L
                                        </span>
str_rice
5.64
int price
564000
span
<span class="text-bold">
                                            6.01L
                                        </span>
str_rice
6.01
int price
601000
span
<span class="text-bold">
                                            6.28L
                                        </span>
str_rice
6.28
int price
628000
span
<span class="text-bold">
                                            6.49L
                                        </span>
str_rice
6.49
int price
649000
span
<span class="text-bold">
                                            6.59L
                                        </span>
str_rice
6.59
int price
659000
span
<span class="text-bold">
                                            6.76L
                                        </span>
str_rice
6.76
int price
676000
span
<span class="text-bold">
                                            7.04L
                                        </span>
str_rice
7.04
int price
704000
span
<span class="text-bold">
                                            7.13L
                                        </span>
str_rice
7.13
int price
713000
span
<span class="text-bold">
                                            7.40L
                                        </span>
str_rice
7.40
int price
740000
span
<span class="text-bold">
                                            7.62L
                                        </span>
str_rice
7.62
int price
762000
span
<span class="text-bold">
                                            8.16L
                                        </span>
str_rice
8.16
int price
816000
total
1800209028059000
avg_price
138477617543000
added Ford Aspire
end
20
span
<span class="block text-bold font16"><span class="price-quote-all-imgs circle-call-icon"></span>18002090230</span>
str_rice
1800209023
int price
1800209020000000
span
<span class="text-bold">
                                            7.24L
                                        </span>
str_rice
7.24
int price
724000
span
<span class="text-bold">
                                            7.91L
                                        </span>
str_rice
7.91
int price
791000
span
<span class="text-bold">
                                            8.02L
                                        </span>
str_rice
8.02
int price
802000
span
<span class="text-bold">
                                            8.63L
                                        </span>
str_rice
8.63
int price
863000
span
<span class="text-bold">
                                            8.71L
                                        </span>
str_rice
8.71
int price
871000
span
<span class="text-bold">
                                            8.94L
                                        </span>
str_rice
8.94
int price
894000
span
<span class="text-bold">
                                            9L
                                        </span>
str_rice
9
int price
900000
span
<span class="text-bold">
                                            9.04L
                                        </span>
str_rice
9.04
int price
903999
span
<span class="text-bold">
                                            9.10L
                                        </span>
str_rice
9.10
int price
910000
span
<span class="text-bold">
                                            9.25L
                                        </span>
str_rice
9.25
int price
925000
span
<span class="text-bold">
                                            9.64L
                                        </span>
str_rice
9.64
int price
964000
span
<span class="text-bold">
                                            9.65L
                                        </span>
str_rice
9.65
int price
965000
span
<span class="text-bold">
                                            9.91L
                                        </span>
str_rice
9.91
int price
991000
span
<span class="text-bold">
                                            9.95L
                                        </span>
str_rice
9.95
int price
994999
span
<span class="text-bold">
                                            10.12L
                                        </span>
str_rice
10.12
int price
1011999
span
<span class="text-bold">
                                            10.17L
                                        </span>
str_rice
10.17
int price
1017000
span
<span class="text-bold">
                                            10.23L
                                        </span>
str_rice
10.23
int price
1023000
span
<span class="text-bold">
                                            10.24L
                                        </span>
str_rice
10.24
int price
1024000
span
<span class="text-bold">
                                            10.56L
                                        </span>
str_rice
10.56
int price
1056000
total
1800209037630997
avg_price
90010451881549
added Ford EcoSport
end
5
span
<span class="text-bold">
                                            24.83L
                                        </span>
str_rice
24.83
int price
2483000
span
<span class="text-bold">
                                            25.28L
                                        </span>
str_rice
25.28
int price
2528000
span
<span class="text-bold">
                                            27.10L
                                        </span>
str_rice
27.10
int price
2710000
span
<span class="text-bold">
                                            28.42L
                                        </span>
str_rice
28.42
int price
2842000
span
<span class="text-bold">
                                            31.32L
                                        </span>
str_rice
31.32
int price
3132000
total
13695000
avg_price
2739000
added Ford Endeavour
end
1
span
<span class="text-bold">
                                            67.91L
                                        </span>
str_rice
67.91
int price
6791000
total
6791000
avg_price
6791000
added Ford Mustang
the url
https://www.carwale.com/honda-cars/
end
4
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Honda Brio

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
15
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Honda Amaze

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
12
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Honda Jazz

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
10
span
<span class="text-bold">
                                            7.55L
                                        </span>
str_rice
7.55
int price
755000
span
<span class="text-bold">
                                            8.65L
                                        </span>
str_rice
8.65
int price
865000
span
<span class="text-bold">
                                            9.09L
                                        </span>
str_rice
9.09
int price
909000
span
<span class="text-bold">
                                            9.87L
                                        </span>
str_rice
9.87
int price
986999
span
<span class="text-bold">
                                            9.97L
                                        </span>
str_rice
9.97
int price
997000
span
<span class="text-bold">
                                            10.54L
                                        </span>
str_rice
10.54
int price
1054000
span
<span class="text-bold">
                                            11.09L
                                        </span>
str_rice
11.09
int price
1109000
span
<span class="text-bold">
                                            11.67L
                                        </span>
str_rice
11.67
int price
1167000
span
<span class="text-bold">
                                            12.26L
                                        </span>
str_rice
12.26
int price
1226000
span
<span class="text-bold">
                                            12.83L
                                        </span>
str_rice
12.83
int price
1283000
total
10351999
avg_price
1035199
added Honda Mobilio
end
16
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Honda City

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
9
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Honda BR-V

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
3
span
<span class="text-bold">
                                            23.03L
                                        </span>
str_rice
23.03
int price
2303000
span
<span class="text-bold">
                                            24.73L
                                        </span>
str_rice
24.73
int price
2473000
span
<span class="text-bold">
                                            27.19L
                                        </span>
str_rice
27.19
int price
2719000
total
7495000
avg_price
2498333
added Honda CR-V
end
1
span
<span class="text-bold">
                                            40.42L
                                        </span>
str_rice
40.42
int price
4042000
total
4042000
avg_price
4042000
added Honda Accord
the url
https://www.carwale.com/hyundai-cars/
end
12
span
<span class="text-bold">
                                            3.31L
                                        </span>
str_rice
3.31
int price
331000
span
<span class="text-bold">
                                            3.57L
                                        </span>
str_rice
3.57
int price
357000
span
<span class="text-bold">
                                            3.69L
                                        </span>
str_rice
3.69
int price
369000
span
<span class="text-bold">
                                            3.81L
                                        </span>
str_rice
3.81
int price
381000
span
<span class="text-bold">
                                            3.84L
                                        </span>
str_rice
3.84
int price
384000
span
<span class="text-bold">
                                            3.99L
                                        </span>
str_rice
3.99
int price
399000
span
<span class="text-bold">
                                            4.03L
                                        </span>
str_rice
4.03
int price
403000
span
<span class="text-bold">
                                            4.11L
                                        </span>
str_rice
4.11
int price
411000
span
<span class="text-bold">
                                            4.16L
                                        </span>
str_rice
4.16
int price
416000
span
<span class="text-bold">
                                            4.32L
                                        </span>
str_rice
4.32
int price
432000
span
<span class="text-bold">
                                            4.49L
                                        </span>
str_rice
4.49
int price
449000
span
<span class="text-bold">
                                            4.59L
                                        </span>
str_rice
4.59
int price
459000
total
4791000
avg_price
399250
added Hyundai Eon
end
4
span
<span class="text-bold">
                                            4.42L
                                        </span>
str_rice
4.42
int price
442000
span
<span class="text-bold">
                                            4.65L
                                        </span>
str_rice
4.65
int price
465000
span
<span class="text-bold">
                                            4.96L
                                        </span>
str_rice
4.96
int price
496000
span
<span class="text-bold">
                                            5.25L
                                        </span>
str_rice
5.25
int price
525000
total
1928000
avg_price
482000
added Hyundai i10
end
12
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Hyundai Grand i10

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
11
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Hyundai Xcent

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
11
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Hyundai Elite i20

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
6
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Hyundai i20 Active

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
12
span
<span class="text-bold">
                                            8.03L
                                        </span>
str_rice
8.03
int price
802999
span
<span class="text-bold">
                                            9.23L
                                        </span>
str_rice
9.23
int price
923000
span
<span class="text-bold">
                                            9.32L
                                        </span>
str_rice
9.32
int price
932000
span
<span class="text-bold">
                                            9.97L
                                        </span>
str_rice
9.97
int price
997000
span
<span class="text-bold">
                                            10.13L
                                        </span>
str_rice
10.13
int price
1013000
span
<span class="text-bold">
                                            10.68L
                                        </span>
str_rice
10.68
int price
1068000
span
<span class="text-bold">
                                            10.80L
                                        </span>
str_rice
10.80
int price
1080000
span
<span class="text-bold">
                                            11.04L
                                        </span>
str_rice
11.04
int price
1104000
span
<span class="text-bold">
                                            11.22L
                                        </span>
str_rice
11.22
int price
1122000
span
<span class="text-bold">
                                            11.39L
                                        </span>
str_rice
11.39
int price
1139000
span
<span class="text-bold">
                                            12.51L
                                        </span>
str_rice
12.51
int price
1251000
span
<span class="text-bold">
                                            13.34L
                                        </span>
str_rice
13.34
int price
1334000
total
12765999
avg_price
1063833
added Hyundai Verna
end
14
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Hyundai Creta

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
9
span
<span class="text-bold">
                                            13.24L
                                        </span>
str_rice
13.24
int price
1324000
span
<span class="text-bold">
                                            15.07L
                                        </span>
str_rice
15.07
int price
1507000
span
<span class="text-bold">
                                            15.07L
                                        </span>
str_rice
15.07
int price
1507000
span
<span class="text-bold">
                                            16.19L
                                        </span>
str_rice
16.19
int price
1619000
span
<span class="text-bold">
                                            16.70L
                                        </span>
str_rice
16.70
int price
1670000
span
<span class="text-bold">
                                            16.90L
                                        </span>
str_rice
16.90
int price
1689999
span
<span class="text-bold">
                                            18.11L
                                        </span>
str_rice
18.11
int price
1811000
span
<span class="text-bold">
                                            18.42L
                                        </span>
str_rice
18.42
int price
1842000
span
<span class="text-bold">
                                            19.65L
                                        </span>
str_rice
19.65
int price
1964999
total
14934998
avg_price
1659444
added Hyundai Elantra
end
5
span
<span class="text-bold">
                                            19.43L
                                        </span>
str_rice
19.43
int price
1943000
span
<span class="text-bold">
                                            22.09L
                                        </span>
str_rice
22.09
int price
2209000
span
<span class="text-bold">
                                            22.30L
                                        </span>
str_rice
22.30
int price
2230000
span
<span class="text-bold">
                                            24.03L
                                        </span>
str_rice
24.03
int price
2403000
span
<span class="text-bold">
                                            25.58L
                                        </span>
str_rice
25.58
int price
2558000
total
11343000
avg_price
2268600
added Hyundai Tucson
end
3
span
<span class="text-bold">
                                            29.11L
                                        </span>
str_rice
29.11
int price
2911000
span
<span class="text-bold">
                                            30.40L
                                        </span>
str_rice
30.40
int price
3040000
span
<span class="text-bold">
                                            32.61L
                                        </span>
str_rice
32.61
int price
3261000
total
9212000
avg_price
3070666
added Hyundai Santa Fe
the url
https://www.carwale.com/jaguar-cars/
end
3
span
<span class="text-bold">
                                            40.73L
                                        </span>
str_rice
40.73
int price
4072999
span
<span class="text-bold">
                                            44.73L
                                        </span>
str_rice
44.73
int price
4473000
span
<span class="text-bold">
                                            48.99L
                                        </span>
str_rice
48.99
int price
4899000
total
13444999
avg_price
4481666
added Jaguar XE
end
5
span
<span class="text-bold">
                                            50.50L
                                        </span>
str_rice
50.50
int price
5050000
span
<span class="text-bold">
                                            57.64L
                                        </span>
str_rice
57.64
int price
5764000
span
<span class="text-bold">
                                            57.89L
                                        </span>
str_rice
57.89
int price
5789000
span
<span class="text-bold">
                                            63.05L
                                        </span>
str_rice
63.05
int price
6305000
span
<span class="text-bold">
                                            63.30L
                                        </span>
str_rice
63.30
int price
6330000
total
29238000
avg_price
5847600
added Jaguar XF
end
4
span
<span class="text-bold">
                                            69.73L
                                        </span>
str_rice
69.73
int price
6973000
span
<span class="text-bold">
                                            78.96L
                                        </span>
str_rice
78.96
int price
7895999
span
<span class="text-bold">
                                            1.20Cr
                                        </span>
str_rice
1.20C
int price
12000000
span
<span class="text-bold">
                                            1.24Cr
                                        </span>
str_rice
1.24C
int price
12400000
total
39268999
avg_price
9817249
added Jaguar F-Pace
end
4
span
<span class="text-bold">
                                            1.02Cr
                                        </span>
str_rice
1.02C
int price
10200000
span
<span class="text-bold">
                                            1.02Cr
                                        </span>
str_rice
1.02C
int price
10200000
span
<span class="text-bold">
                                            1.10Cr
                                        </span>
str_rice
1.10C
int price
11000000
span
<span class="text-bold">
                                            2.08Cr
                                        </span>
str_rice
2.08C
int price
20800000
total
52200000
avg_price
13050000
added Jaguar XJ L
end
5
span
<span class="text-bold">
                                            1.26Cr
                                        </span>
str_rice
1.26C
int price
12600000
span
<span class="text-bold">
                                            1.44Cr
                                        </span>
str_rice
1.44C
int price
14400000
span
<span class="text-bold">
                                            1.57Cr
                                        </span>
str_rice
1.57C
int price
15700000
span
<span class="text-bold">
                                            1.94Cr
                                        </span>
str_rice
1.94C
int price
19400000
span
<span class="text-bold">
                                            1.96Cr
                                        </span>
str_rice
1.96C
int price
19600000
total
81700000
avg_price
16340000
added Jaguar F-Type
the url
https://www.carwale.com/landrover-cars/
end
8
span
<span class="text-bold">
                                            48.76L
                                        </span>
str_rice
48.76
int price
4876000
span
<span class="text-bold">
                                            54L
                                        </span>
str_rice
54
int price
5400000
span
<span class="text-bold">
                                            55.56L
                                        </span>
str_rice
55.56
int price
5556000
span
<span class="text-bold">
                                            56.61L
                                        </span>
str_rice
56.61
int price
5661000
span
<span class="text-bold">
                                            58.15L
                                        </span>
str_rice
58.15
int price
5815000
span
<span class="text-bold">
                                            59.09L
                                        </span>
str_rice
59.09
int price
5909000
span
<span class="text-bold">
                                            64.22L
                                        </span>
str_rice
64.22
int price
6422000
span
<span class="text-bold">
                                            65.77L
                                        </span>
str_rice
65.77
int price
6577000
total
46216000
avg_price
5777000
added Land Rover Discovery Sport
end
5
span
<span class="text-bold">
                                            49.80L
                                        </span>
str_rice
49.80
int price
4980000
span
<span class="text-bold">
                                            55.50L
                                        </span>
str_rice
55.50
int price
5550000
span
<span class="text-bold">
                                            59.22L
                                        </span>
str_rice
59.22
int price
5922000
span
<span class="text-bold">
                                            60.83L
                                        </span>
str_rice
60.83
int price
6083000
span
<span class="text-bold">
                                            66.56L
                                        </span>
str_rice
66.56
int price
6656000
total
29191000
avg_price
5838200
added Land Rover Range Rover Evoque
end
2
span
<span class="text-bold">
                                            1.14Cr
                                        </span>
str_rice
1.14C
int price
11399999
span
<span class="text-bold">
                                            1.22Cr
                                        </span>
str_rice
1.22C
int price
12200000
total
23599999
avg_price
11799999
added Land Rover Discovery
end
7
span
<span class="text-bold">
                                            1.20Cr
                                        </span>
str_rice
1.20C
int price
12000000
span
<span class="text-bold">
                                            1.28Cr
                                        </span>
str_rice
1.28C
int price
12800000
span
<span class="text-bold">
                                            1.35Cr
                                        </span>
str_rice
1.35C
int price
13500000
span
<span class="text-bold">
                                            1.50Cr
                                        </span>
str_rice
1.50C
int price
15000000
span
<span class="text-bold">
                                            1.56Cr
                                        </span>
str_rice
1.56C
int price
15600000
span
<span class="text-bold">
                                            1.81Cr
                                        </span>
str_rice
1.81C
int price
18100000
span
<span class="text-bold">
                                            2.11Cr
                                        </span>
str_rice
2.11C
int price
21100000
total
108100000
avg_price
15442857
added Land Rover Range Rover Sport
end
11
span
<span class="text-bold">
                                            2.16Cr
                                        </span>
str_rice
2.16C
int price
21600000
span
<span class="text-bold">
                                            2.16Cr
                                        </span>
str_rice
2.16C
int price
21600000
span
<span class="text-bold">
                                            2.29Cr
                                        </span>
str_rice
2.29C
int price
22900000
span
<span class="text-bold">
                                            2.59Cr
                                        </span>
str_rice
2.59C
int price
25900000
span
<span class="text-bold">
                                            2.67Cr
                                        </span>
str_rice
2.67C
int price
26700000
span
<span class="text-bold">
                                            2.69Cr
                                        </span>
str_rice
2.69C
int price
26900000
span
<span class="text-bold">
                                            2.74Cr
                                        </span>
str_rice
2.74C
int price
27400000
span
<span class="text-bold">
                                            2.80Cr
                                        </span>
str_rice
2.80C
int price
28000000
span
<span class="text-bold">
                                            2.94Cr
                                        </span>
str_rice
2.94C
int price
29400000
span
<span class="text-bold">
                                            3.98Cr
                                        </span>
str_rice
3.98C
int price
39800000
span
<span class="text-bold">
                                            3.98Cr
                                        </span>
str_rice
3.98C
int price
39800000
total
310000000
avg_price
28181818
added Land Rover Range Rover
the url
https://www.carwale.com/mahindra-cars/
end
24
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Mahindra KUV100

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
5
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Mahindra Thar

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
19
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Mahindra Bolero

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
3
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Mahindra Verito Vibe CS

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
3
span
<span class="text-bold">
                                            6.79L
                                        </span>
str_rice
6.79
int price
679000
span
<span class="text-bold">
                                            7.20L
                                        </span>
str_rice
7.20
int price
720000
span
<span class="text-bold">
                                            10L
                                        </span>
str_rice
10
int price
1000000
total
2399000
avg_price
799666
added Mahindra e2o Plus
end
6
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Mahindra Verito

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
9
span
<span class="text-bold">
                                            7.53L
                                        </span>
str_rice
7.53
int price
753000
span
<span class="text-bold">
                                            7.90L
                                        </span>
str_rice
7.90
int price
790000
span
<span class="text-bold">
                                            8.21L
                                        </span>
str_rice
8.21
int price
821000
span
<span class="text-bold">
                                            8.47L
                                        </span>
str_rice
8.47
int price
847000
span
<span class="text-bold">
                                            9.10L
                                        </span>
str_rice
9.10
int price
910000
span
<span class="text-bold">
                                            9.18L
                                        </span>
str_rice
9.18
int price
918000
span
<span class="text-bold">
                                            9.21L
                                        </span>
str_rice
9.21
int price
921000
span
<span class="text-bold">
                                            9.84L
                                        </span>
str_rice
9.84
int price
984000
span
<span class="text-bold">
                                            9.94L
                                        </span>
str_rice
9.94
int price
994000
total
7938000
avg_price
882000
added Mahindra TUV300
end
6
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Mahindra NuvoSport

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
7
span
<span class="text-bold">
                                            8.83L
                                        </span>
str_rice
8.83
int price
883000
span
<span class="text-bold">
                                            8.98L
                                        </span>
str_rice
8.98
int price
898000
span
<span class="text-bold">
                                            9.28L
                                        </span>
str_rice
9.28
int price
927999
span
<span class="text-bold">
                                            9.44L
                                        </span>
str_rice
9.44
int price
944000
span
<span class="text-bold">
                                            9.62L
                                        </span>
str_rice
9.62
int price
961999
span
<span class="text-bold">
                                            9.91L
                                        </span>
str_rice
9.91
int price
991000
span
<span class="text-bold">
                                            11.51L
                                        </span>
str_rice
11.51
int price
1151000
total
6756998
avg_price
965285
added Mahindra Xylo
end
4
span
<span class="text-bold">
                                            8.99L
                                        </span>
str_rice
8.99
int price
899000
span
<span class="text-bold">
                                            9.21L
                                        </span>
str_rice
9.21
int price
921000
span
<span class="text-bold">
                                            9.99L
                                        </span>
str_rice
9.99
int price
999000
span
<span class="text-bold">
                                            10.22L
                                        </span>
str_rice
10.22
int price
1022000
total
3841000
avg_price
960250
added Mahindra Scorpio Getaway
end
17
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Mahindra Scorpio

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
19
span
<span class="text-bold">BIG</span>
str_rice
BI
in except
price not found for Mahindra XUV500
the url
https://www.carwale.com/marutisuzuki-cars/

Traceback (most recent call last):
  File "<ipython-input-7-bc616ddb4987>", line 29, in car_detail
    int_price = int(float(str_price[:-2]) * 10000000)
ValueError: could not convert string to float: 'B'

end
10
span
<span class="text-bold">
                                            2.61L
                                        </span>
str_rice
2.61
int price
261000
span
<span class="text-bold">
                                            2.67L
                                        </span>
str_rice
2.67
int price
267000
span
<span class="text-bold">
                                            2.96L
                                        </span>
str_rice
2.96
int price
296000
span
<span class="text-bold">
                                            3.02L
                                        </span>
str_rice
3.02
int price
302000
span
<span class="text-bold">
                                            3.22L
                                        </span>
str_rice
3.22
int price
322000
span
<span class="text-bold">
                                            3.28L
                                        </span>
str_rice
3.28
int price
328000
span
<span class="text-bold">
                                            3.41L
                                        </span>
str_rice
3.41
int price
341000
span
<span class="text-bold">
                                            3.47L
                                        </span>
str_rice
3.47
int price
347000
span
<span class="text-bold">
                                            3.84L
                                        </span>
str_rice
3.84
int price
384000
span
<span class="text-bold">
                                            3.90L
                                        </span>
str_rice
3.90
int price
390000
total
3238000
avg_price
323800
added Maruti Suzuki Alto 800